export default {
    firstname: 'नाव*',
    middlename: 'मधले नाव',
    lastname: 'आडनाव*',
    dob: 'जन्मतारीख',
    mothertongue: 'मातृभाषा',
    caste: 'cast',
    mobile: 'मोबाईल*',
    education: 'शिक्षण',
    jobdesc: 'व्यवसाय',
    email: 'ईमेल',
    houseno: 'घर क्र',
    buildingname: 'इमारत नाव',
    area: 'परीसर',
    pincode: 'पिनकोड',
    //vidhansabha: '',
    aadharcardno: 'आधार कार्ड नं',
    votercardno: 'मतदार ओळखपत्र क्रमांक*',
    department: 'पार्टी विंग',
    designation: 'पोस्ट',
    wardno: 'प्रभाग क्रमांक*' ,
    boothno: 'बूथ क्रमांक *',
    gender: 'लिंग',
  }